### ISSUE TITLE
Telepot Issue

### ISSUE THREAD

**Issue by BrilliantImagination** [converge/instapy_telegram_extension#3]
I get this error code when trying to start my script. Hope there is an easy fix.

 Traceback (most recent call last):
  File "legendy-2018-04.py", line 2, in <module>
    from extensions.instapy_telegram_extension import InstaPyTelegramExtension
  File "/Users/legendy/Documents/InstaPy/extensions/instapy_telegram_extension/InstaPyTelegramExtension.py", line 5, in <module>
    import telepot
ModuleNotFoundError: No module named 'telepot'

**Comment by converge** [comment]
pip install telepot
or
pip3 install telepot
